export const ALL_PROCESSOR_ITEM = "ALL_PROCESSOR_ITEM";
export const ADD_RESULT = "ADD_RESULT";
export const SHOPPING_CART = "SHOPPING_CART";
export const SHOPPING_CART_LENGTH = "SHOPPING_CART_LENGTH";
export const ADD_ID_ARR = "ADD_ID_ARR";
export const FILTER_ITEMS = "FILTER_ITEMS";
